(cl:defpackage yoloswag-srv
  (:use )
  (:export
   "RECORDAUDIO"
   "<RECORDAUDIO-REQUEST>"
   "RECORDAUDIO-REQUEST"
   "<RECORDAUDIO-RESPONSE>"
   "RECORDAUDIO-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

