/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/vishalsai/Documents/PR2Research/pr2go/v3ws/src/yoloswag/srv/RecordAudio.srv
 *
 */


#ifndef YOLOSWAG_MESSAGE_RECORDAUDIOREQUEST_H
#define YOLOSWAG_MESSAGE_RECORDAUDIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yoloswag
{
template <class ContainerAllocator>
struct RecordAudioRequest_
{
  typedef RecordAudioRequest_<ContainerAllocator> Type;

  RecordAudioRequest_()
    : d(0)
    , cmds()  {
    }
  RecordAudioRequest_(const ContainerAllocator& _alloc)
    : d(0)
    , cmds(_alloc)  {
    }



   typedef int64_t _d_type;
  _d_type d;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _cmds_type;
  _cmds_type cmds;




  typedef boost::shared_ptr< ::yoloswag::RecordAudioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yoloswag::RecordAudioRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RecordAudioRequest_

typedef ::yoloswag::RecordAudioRequest_<std::allocator<void> > RecordAudioRequest;

typedef boost::shared_ptr< ::yoloswag::RecordAudioRequest > RecordAudioRequestPtr;
typedef boost::shared_ptr< ::yoloswag::RecordAudioRequest const> RecordAudioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yoloswag::RecordAudioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yoloswag

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg'], 'yoloswag': ['/home/vishalsai/Documents/PR2Research/pr2go/v3ws/src/yoloswag/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yoloswag::RecordAudioRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yoloswag::RecordAudioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yoloswag::RecordAudioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d51782f63141dfbce4a66ec61e781595";
  }

  static const char* value(const ::yoloswag::RecordAudioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd51782f63141dfbcULL;
  static const uint64_t static_value2 = 0xe4a66ec61e781595ULL;
};

template<class ContainerAllocator>
struct DataType< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yoloswag/RecordAudioRequest";
  }

  static const char* value(const ::yoloswag::RecordAudioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 d\n\
string[] cmds\n\
\n\
";
  }

  static const char* value(const ::yoloswag::RecordAudioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.d);
      stream.next(m.cmds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RecordAudioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yoloswag::RecordAudioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yoloswag::RecordAudioRequest_<ContainerAllocator>& v)
  {
    s << indent << "d: ";
    Printer<int64_t>::stream(s, indent + "  ", v.d);
    s << indent << "cmds[]" << std::endl;
    for (size_t i = 0; i < v.cmds.size(); ++i)
    {
      s << indent << "  cmds[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOSWAG_MESSAGE_RECORDAUDIOREQUEST_H
